### ISSUE TITLE
Issue when opening file

### ISSUE THREAD

**Issue by tscrip** [somax/extension-jse#1]
I am not able to get it to run. It tells me that a favicon is missing. Also, the path that it provides does not exist. Does it unzip the contents of the .jse file into /node_modules/extension-jse/lib? That is the path where it says that the file is missing.

**fs.js:892**
  **return binding.stat(pathModule._makeLong(path));**

**Error: ENOENT: no such file or directory, stat** **'/Users/<USERNAME>/Development/Node/<PROJECT>/node_modules/extension-jse/lib/frontend/img/favicon.ico'**

**Comment by somax** [comment]
It doesn't unzip any file to disk,  it just in memory.
